package fr.xebia.jqwik.exercise5;

import net.jqwik.api.Assume;
import net.jqwik.api.ForAll;
import net.jqwik.api.Property;
import net.jqwik.api.lifecycle.BeforeTry;

import java.util.Objects;

import static org.mockito.BDDMockito.then;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.reset;

class AlertRoutingServiceTest {

    private static final Country ITALY = new Country("IT");
    private static final Country USA = new Country("US");

    private final NotificationServiceForItaly notificationServiceForItaly = mock(NotificationServiceForItaly.class);
    private final NotificationServiceForUsa notificationServiceForUsa = mock(NotificationServiceForUsa.class);
    private final DefaultNotificationService defaultNotificationService = mock(DefaultNotificationService.class);
    private final AlertRoutingService routingService = new AlertRoutingService(notificationServiceForItaly, notificationServiceForUsa, defaultNotificationService);

    @BeforeTry
    void resetInteractionCount() {
        // Calling Mockito.reset between each try is necessary so that interaction count is reset between examples generated by Jqwik.
        reset(defaultNotificationService);
    }

    @Property
    void should_send_alert_to_specific_service_for_Italian_alert(@ForAll Alert.Type type) {
        final Alert alert = new Alert(type, ITALY);

        routingService.send(alert);

        then(notificationServiceForItaly).should().notify(type.getCodeForItaly());
        then(notificationServiceForUsa).shouldHaveNoInteractions();
        then(defaultNotificationService).shouldHaveNoInteractions();
    }

    @Property
    void should_send_alert_code_to_specific_service_for_US_alert(@ForAll Alert.Type type) {
        final Alert alert = new Alert(type, USA);

        routingService.send(alert);

        then(notificationServiceForItaly).shouldHaveNoInteractions();
        then(notificationServiceForUsa).should().notify(type.getCodeForUsa());
        then(defaultNotificationService).shouldHaveNoInteractions();
    }

    /**
     * TODO: Define alert as an argument to the test method, instead of type and country.
     * <hr/>
     * <p>Hint #1: Define a provider class in order to generate parameter depending on already-existing providers. Cf. <a href="https://jqwik.net/docs/current/user-guide.html#combining-arbitraries">Combining arbitraries</a></p>
     * <p>Hint #2: You can define a custom annotation in order to generate alerts for standard countries only. Cf. <a href="https://jqwik.net/docs/current/user-guide.html#create-your-own-annotations-for-arbitrary-configuration">Create your own annotations for arbitrary configuration</a></p>
     */
    @Property
    void should_send_alert_message_to_default_service_for_alert_of_standard_country(@ForAll Alert.Type type, @ForAll Country country) {
        Assume.that(! Objects.equals(country, ITALY));
        Assume.that(! Objects.equals(country, USA));
        final Alert alert = new Alert(type, country);

        routingService.send(alert);

        then(notificationServiceForItaly).shouldHaveNoInteractions();
        then(notificationServiceForUsa).shouldHaveNoInteractions();
        then(defaultNotificationService).should().notify(alert.getType().getDefaultMessage());
    }

}
